apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: hpa-access
rules:
- apiGroups: ["autoscaling"]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "watch", "list", "create", "delete"]
